### ISSUE TITLE
Make Issues for Defining Marketing Objectives for all Projects

### ISSUE THREAD

**Issue by chiusano** [hackforla/marketing#14]
### Overview
We need to make a template for each project in order to collect consistent information organization-wide.

### Action Items:

- [x] Make a list of all active projects from Hack for LA homepage
- [x] Make an issue for each one using the template

### List of Projects:

- [x] 100 Automations
- [x] 311 Data
- [x] BallotNav
- [x] Civic Opportunity Project
- [x] Civic Tech Index
- [x] Civic Tech Structure
- [x] Engage
- [x] Food Oasis
- [x] Hackforla.org Website
- [x] Home Unite Us
- [x] KLA TDM Calculator
- [x] Lucky Parking
- [x] Public Tree Map
- [x] Record Clearance Project
- [x] Undebate
- [x] VRMS
- [x] Write for All
- [x] Youth Justice Nav

### Resources
[Template for any project](https://github.com/hackforla/marketing/issues/new?assignees=&labels=documentation%2C+Level%3A+Learning%2C+Skill%3A+Digital+Marketing%2C+Skill%3A+Media+Strategy%2C+Skill%3A+Brand+Strategy&template=custom-issuedefine-marketing-objectives-for--insert-project-name--projecttemplate.md&title=Define+Marketing+Objectives+for+%5BINSERT+PROJECT+NAME%5D+project)

**Comment by ExperimentsInHonesty** [comment]
A issue template got made and new issues were created for each project
