### ISSUE TITLE
Review new Recruiting Pipeline channel

### ISSUE THREAD

**Issue by Civic-Opportunity-Project** [hackforla/marketing#49]
[Pipeline sheet](https://docs.google.com/spreadsheets/d/19VBho1i-3kmteCUy-T0SsMu2NdblOblI_s2cVRxdC8U/edit)

- [ ] Review Digital Marketing (LinkedIn group) in Row 10
- [ ] Set Display value (column L) to TRUE or FALSE

**Comment by rjdoria** [comment]
Zapier test completed. Pipeline doc now live.
