### ISSUE TITLE
Prep project boards for Migration

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/marketing#59]
### Overview
We need to prepare the Project Boards for the forced migration that GitHub is doing in August, so that it is already working well for the team by then.

### Action Items
- [x]  copy this template to a comment below
   ````
   ### Text from project board card, [Add name of column here]
   ```
   [INSERT MARKDOWN HERE]
   ```
   - [ ] Determine where this item goes on the wiki (page and section)
   - [ ] copy item to wiki
   - [ ] hide this comment when completed.
   ````
- [x] copy markdown from a card in the "Start Here" column of the Project Board into your new comment, where it says `[INSERT MARKDOWN HERE]
- [x] delete card from project board.

### Resources/Instructions
Project board URL:

**Comment by ExperimentsInHonesty** [comment]
### Text from Marketing Open Roles project board card, Instructions
```
# START HERE
We know this board is ugly!!!

- [Find a volunteer Opportunity](https://github.com/hackforla/marketing/projects/4#card-53860226)
- [Post a volunteer Opportunity](https://github.com/hackforla/marketing/projects/4#card-53860215)
- [Remove a volunteer Opportunity](https://github.com/hackforla/marketing/projects/4#card-53860183)

If you know some places where we should post these opportunities please [submit Marketing channels](https://docs.google.com/forms/d/e/1FAIpQLScDrgJHndp48GUbbpj4mlkbqYM0nuaU0Rr6WojKCXM9k9iNNA/viewform) after you check to make sure its not on the list of [existing Marketing channels we know about](https://docs.google.com/spreadsheets/d/19VBho1i-3kmteCUy-T0SsMu2NdblOblI_s2cVRxdC8U/preview)

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Diversity, Equity and Inclusion
```
Write For All
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Citizen Engagement
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Citizen Engagement
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Citizen Engagement
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Citizen Engagement
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Citizen Engagement
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
Civic Tech Index

- #48

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Justice
```
HomeUniteUs
Food Oasis
- #40
Youth Justice Nav
Heart
Expunge-Assist
- #42
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Voting and Representation
```
BallotNav
- #41
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Workforce Development
```
Website
Internship Project
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project level marketing info, Various
```
Data Science Projects
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Organizational Marketing, Links/Questions/Review
```
Messaging Document
[Messaging Document](https://docs.google.com/document/d/1QM8FfScmqUixykckXmB2qG5Y3jY6Tpp_2dDXt8Ez4gA/edit?usp=sharing)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Organizational Marketing, Links/Questions/Review
```
Hack for LA social media links
- [Youtube temp link](https://www.youtube.com/channel/UCOl_a9rl1FykCd3ZO0yN6uQ)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Marketing, Ice Box
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Marketing, Ice Box
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Marketing, Ice Box
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Marketing, Ice Box
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Marketing, Ice Box
```

```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Marketing, New Issue Approval
```
Make a Collect Marketing Assets for Guides
There is no issue in their repo
There is a link to their one sheet in the [wiki](https://github.com/hackforla/guides/wiki)
their figma has logos
there are bios someplace
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by Rabia2219** [comment]
### Text from project board card, Project Marketing, Links/Questions/Review
```
Templates for projects
- [Marketing Objective Project Survey template](https://github.com/hackforla/marketing/issues/new?assignees=&labels=Level%3A+Learning%2C+Skill%3A+Brand+Strategy%2C+Skill%3A+Digital+Marketing%2C+Skill%3A+Media+Strategy%2C+documentation&template=define-marketing-objectives-for--insert-project-name-.md&title=Define+Marketing+Objectives+for+%5BINSERT+PROJECT+NAME%5D+project)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
[issues tab with PA labels excluded](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+project%3Ahackforla%2F7+-label%3A%22PA%3A+Citizen+Engagement%22+-label%3A%22PA%3A+Civic+Tech+Infrastructure%22+-label%3A%22PA%3A+Diversity+Equity+and+Inclusion%22+-label%3A%22PA%3A+Environmental%22+-label%3A%22PA%3A+Justice%22+-label%3A%22PA%3A+Social+Safety+Net%22+-label%3A%22PA%3A+Voting+and+Representation%22)

**Comment by ExperimentsInHonesty** [comment]
100 Automations issue status: Well documented (has social links and assets) 
- #36

**Comment by ExperimentsInHonesty** [comment]
- Add labels for all projects to the marketing board.  See/Copy the list of the ones needed 
- We need to create a marketing issue for each cop in this repository, and then add that issue to the [Marketing board, CoPs tab](https://github.com/orgs/hackforla/projects/111/views/6) and the board of each CoP.

- [ ] Create an epic issue to do the following
```
### Action Items
- [ ] Search for general marketing issues on Issue tab (resource 1.01) and add issues to a comment on this issue under this heading
   ```
   [Name of project] Team Task board issues
   ```
- [ ] Seach the project's repo for any marketing issues, add any links you find to the the same comment
   ```
   Project's repo issues
   ```
- [ ] Review marketing issues
- [ ] Create template
- [ ] Create epic issues for each CoP
- [ ] link all the child issues we already have to the epic for the cop
- [ ] Add the epic issue to their project board and cop product management agenda for discussion

### Resources
- 1.01 [Marketing Repo, Issue Tab, label:"project todo"](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22project+todo%22)
```

**Comment by ExperimentsInHonesty** [comment]
- [ ] Fix the labels on https://github.com/hackforla/marketing/issues/62
- [ ] Update the data columns
   - [ ] Main Repo URL (B)
   - [ ] PA (column D)
   - [ ] S (column F)
   - [ ] Archived (G)

**Comment by ExperimentsInHonesty** [comment]
- [ ] Clean up project boards list on wiki homepage: https://github.com/hackforla/marketing/wiki
- [ ] Make a list of what we have done so far, and what we are doing next, so that we can recruit new marketing CoP lead

**Comment by ExperimentsInHonesty** [comment]
next product Cop I want to be able to see how many teams are missing which issues, so that I can help them make the issue during the cop

list of project links to the tasks board

**Comment by ExperimentsInHonesty** [comment]
### Issues by project
P: 311 Data
P: [BallotNav](https://github.com/hackforla/marketing/issues?q=is%3Aopen+is%3Aissue+label%3A%22P%3A+BallotNav%22)
P: Brigade Organizers Playbook
P: Civic Tech Jobs
P: Expunge Assist
P: Food Oasis
P: Guides
P: HfLA Site
P: Home Unite Us
P: Tech Work Experience
P: Knowledgebase
P: Lucky Parking
P: Open Community Survey
P: People Depot
P: Tables
P: TDM Calculator
P: VRMS
CoP: Admin
CoP: All
CoP: All: Book Club
CoP: Data Science
CoP: Devops
CoP: Engineering
CoP: Marketing
CoP: PM
CoP: UI/UX

**Comment by Rabia2219** [comment]
#### Issues on the drive migration repo for review (no project labels)

- https://github.com/hackforla/google-drive-migration/issues/26
- https://github.com/hackforla/google-drive-migration/issues/36
- https://github.com/hackforla/google-drive-migration/issues/30

**Comment by ExperimentsInHonesty** [comment]
- [Team Tasks board, marketing tab, feature: **marketing objectives]**(https://github.com/orgs/hackforla/projects/7/views/9?filterQuery=label%3A%22project+todo%22++repo%3A%22hackforla%2Fmarketing%22+label%3A%22feature%3A+marketing+objectives%22)
- [Team Tasks board, marketing tab, feature: **project marketing epic**](https://github.com/orgs/hackforla/projects/7/views/9?filterQuery=label%3A%22project+todo%22++repo%3A%22hackforla%2Fmarketing%22++label%3A%22feature%3A+project+marketing+epic%22)
- [Team Tasks board, marketing tab, feature: **marketing inventory checklist**](https://github.com/orgs/hackforla/projects/7/views/9?filterQuery=label%3A%22project+todo%22++repo%3A%22hackforla%2Fmarketing%22+label%3A%22feature%3A+marketing+inventory+checklist%22)

**Comment by ExperimentsInHonesty** [comment]
Copy this to product wiki

- [HfLA: Project Team Tasks](https://github.com/orgs/hackforla/projects/7)
  - [All issues tab](https://github.com/orgs/hackforla/projects/7)
  - [Google Drive Migration tab](https://github.com/orgs/hackforla/projects/7/views/5)
  - [Calendaring tab](https://github.com/orgs/hackforla/projects/7/views/7)
  - [Marketing tab](https://github.com/orgs/hackforla/projects/7/views/9)
  - [Accomplishments tab](https://github.com/orgs/hackforla/projects/7/views/10)
  - [Program Areas tab](https://github.com/orgs/hackforla/projects/7/views/11)
    - [all](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+all%22)
    - [Citizen Engagement](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+Citizen+Engagement%22)
    - [Civic Tech Infrastructure](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+Civic+Tech+Infrastructure%22)
    - [Diversity Equity and Inclusion](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+Diversity+Equity+and+Inclusion%22)
    - [Environment](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+Environment%22)  
    - [Justice](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+Justice%22)
    - [Social Safety Net](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+Social+Safety+Net%22)
    - [Voting and Representation](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+Voting+and+Representation%22)
    - [Workforce Development](https://github.com/orgs/hackforla/projects/7/views/11?filterQuery=label%3A%22epic%22+label%3A%22PA%3A+Workforce+Development%22)

**Comment by Rabia2219** [comment]
```
Proper Website App and Analytics
What are the analytic platforms being used?
Opportunities for better tracking.
create a template to drill down on what they are doing for analytics on their project
```
### Dependencies

### Overview
We need to create a list of what analytics tools our project is using so that we can 

### Action Items
- [ ] Gather a list of tools/platforms currently being used
- [ ] Identify what metrics are being tracked
   - [ ] Are there any other metrics that need to be tracked?
- [ ] Are there any newer/better tracking methods that can be implemented

### Resources/Instructions
-

**Comment by ExperimentsInHonesty** [comment]
- [ ] find the old folder for reading list and add a link to it in Drive Audit: Reading List google-drive-migration#30

**Comment by ExperimentsInHonesty** [comment]
replace missing labels on this issue

**Comment by ExperimentsInHonesty** [comment]
- First create a copy of this Create project and CoP marketing epics #62 https://github.com/hackforla/marketing/issues/62
- Customize
- Create a copy of this template in the above customized version [Step 1: Create Marketing Epic for your project or CoP](https://github.com/hackforla/marketing/issues/new?assignees=&labels=feature%3A+project+marketing+epic%2C+Level%3A+Learning%2C+Marketing+Type%3A+Project%2C+milestone%3A+missing%2C+PA%3A+missing%2C+project+todo%2C+role%3A+marketing+manager%2C+S%3A+missing%2C+size%3A+0.25pt%2C+Skill%3A+Marketing+Operations%2C+Skill%3A+Project+Management&projects=&template=step-1--create-marketing-epic-for-your-project-or-cop.md&title=Epic%3A+Marketing%3A+%5BName+of+Project%5D)
- Make a template inside first issue for [Write summaries of annual accomplishments for website](https://github.com/hackforla/admin-accomplishments/issues/1) - but title it "accomplishment summary for website [YYYY]"

**Comment by Rabia2219** [comment]
## Copy of Create project and CoP marketing epics

```
### Overview
We need to create epic issues for each project and CoP so that we can manage their marketing issues

#### Details
Management includes
- Identifying missing issues
- Creating new issues
- recruiting new team members for marketing roles to work on the issues
- setting standards

### Action Items
- [ ] Create template
- [ ] Test template by creating one issue for a single project
- [ ] Get sign-off by org rep
- [ ] Marketing Manager turns into issue template, adds to Resources section (2.01)
- [ ] Create epic issues for your project or CoP by using the template issue (resource 2.01)
  - Customize epic issue by adding
    - [ ] project name in title
    - [ ] project name in body
    - [ ] project name in resource 2.01
    - project repo issue tab link on resource 2.02
      - [ ] Go to the list of label spreadsheet (this issues resource 1.01)
      - [ ] copy URL from column D (Main Repo URL, Issues tab)
      - [ ] Paste URL on resource 2.02
- [ ] Click on Submit New Issue
- Replace the PA and S missing labels with their values from (resource 1.01)
   - [ ] PA (column E)
   - [ ] S (column G)
- Add new epic issue to the following boards
   - [ ] CoP: Marketing: Project Board
   - [ ] HfLA: Project Team Tasks
   - [ ] Your team's project board
- [ ] Move issue to New issue approval column
- [ ] Add the label `ready for prioritization`
- [ ] Add link to epic created (resources 2.02 in this issue), unless you are doing this in the product-management CoP meeting, in which case, paste it into the chat so that one person can do all the updates.

### Resources
#### Provided by this issue
- 1.01 [List of Project Name Labels](https://docs.google.com/spreadsheets/d/14pzhhBXBsD-l1zrHoAfS7b7KVZ6_RgIH_0gWW9EaqV4)
#### Created by working on this issue
- 2.01 Issue Template [Create Marketing Epic for your project or CoP](https://github.com/hackforla/marketing/issues/new?assignees=&labels=feature%3A+project+marketing+epic%2C+Level%3A+Learning%2C+Marketing+Type%3A+Project%2C+milestone%3A+missing%2C+PA%3A+missing%2C+project+todo%2C+role%3A+marketing+manager%2C+S%3A+missing%2C+size%3A+0.25pt%2C+Skill%3A+Marketing+Operations%2C+Skill%3A+Project+Management&projects=&template=step-1--create-marketing-epic-for-your-project-or-cop.md&title=Epic%3A+Marketing%3A+%5BName+of+Project%5D)
- 2.02 Epic issues created
   - https://github.com/hackforla/marketing/issues/61 - was the test issue created and is now the example for making other project issues
   - https://github.com/hackforla/marketing/issues/63 - example issue for CoP

```
